TreatApp/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TreatApp.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    [Required(ErrorMessage = "The Treat's name can't be empty!")]
    public string Name { get; set; }
    [Required(ErrorMessage = "The Treat's description can't be empty!")]
    public string Description { get; set; }
    public float Price { get; set; }
    public List<TreatFlavor> JoinEntities { get;}
    public ApplicationUser User { get; set; }

  }
}

TreatApp/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using TreatApp.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace TreatApp.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly TreatAppContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, TreatAppContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<IActionResult> Index(string sortOrder)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Treat> userTreats = _db.Treats
                          .Where(entry => entry.User.Id == currentUser.Id)
                          .Include(treat => treat.JoinEntities)
                          .ToList();
      // return View(userTreats);

      var treats = from r in userTreats
                   select r;

      switch (sortOrder)
      {
        case "name_desc":
          treats = userTreats.OrderBy(r => r.Name);
          break;
        case "price_desc":
          treats = userTreats.OrderByDescending(r => r.Price);
          break;
        default:
          treats = userTreats.OrderBy(r => r.TreatId);
          break;
      }
      return View(treats);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        treat.User = currentUser;
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
          .Include(treat => treat.JoinEntities)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      //ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisTreat);
    }


    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
#nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }
    [HttpPost]

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TreatApp/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Treat

<h2>Add a flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TreatApp/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Treat

<h4>Add a new treat</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  @Html.LabelFor(model => model.Price)
  @Html.TextBoxFor(model => model.Price)

  <input type="submit" value="Add new treat" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all treats", "Index")</p>

TreatApp/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Treat

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

TreatApp/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using TreatApp.Models
@model TreatApp.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>   
<h3>@Html.DisplayNameFor(model => model.Price): @Html.DisplayFor(model => model.Price)</h3>   


@if(@Model.JoinEntities.Count == 0)
{
  <p>This treat does not have any flavors yet!</p>
}
else
{
  <h4>This treat has the following flavors:</h4>
  <ul>
    @foreach(TreatFlavor join in Model.JoinEntities)
    {
      <li>Flavor: @join.Flavor.Description</li>
      @using (Html.BeginForm("DeleteJoin", "Treats"))
      {
        @Html.Hidden("joinId", @join.TreatFlavorId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

TreatApp/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Treat

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.Price)
  @Html.EditorFor(model => model.Price)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TreatApp/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}
@model IEnumerable<TreatApp.Models.Treat>
@using TreatApp.Models;
@{

  ViewData["Title"] = "Index";
}

<h1>Treats for @User.Identity.Name</h1>

<table class="table">
    <thead>
        <tr>
                <th>
                        <a href='/Treats?sortOrder=name_desc'>
                        @Html.DisplayNameFor(model => model.Name)</a>

                </th>
                <th>
                        <a href='/Treats?sortOrder=price_desc'>
                        @Html.DisplayNameFor(model => model.Price)</a>
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@if (!Model.Any())
{
  <h3>No treats have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <tr>
        <td><li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li></td>
        <td><li>@Html.ActionLink($"{treat.Price}", "Details", new { id = treat.TreatId })</li></td>
      </tr>
    }
  </ul>
}
    </tbody>
    </table>
<p>@Html.ActionLink("Add new treat", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>