TreatApp/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TreatApp.Models
{
  public class Flavor
  {
    public int FlavorId { get; set; }
    [Required(ErrorMessage = "The Flavor's description can't be empty!")]
    public string Description { get; set; }
    public List<TreatFlavor> JoinEntities { get;}
    public ApplicationUser User { get; set; }

  }
}

TreatApp/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using TreatApp.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TreatApp.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly TreatAppContext _db;

    public FlavorsController(TreatAppContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Description");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      if (joinEntity == null && treatId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

TreatApp/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Flavor

<h2>Add an treat</h2>

<h4>Add an treat to this flavor: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TreatApp/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Flavor

<h4>Add a new flavor</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)

    <input type="submit" value="Add new flavor" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

TreatApp/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

TreatApp/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using TreatApp.Models
@model TreatApp.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This flavor does not belong to any treats</p>
}
else
{
  <h4>Treats the flavor belongs to:</h4>
  <ul>
  @foreach(TreatFlavor join in Model.JoinEntities)
  {
    <li>@join.Treat.Name</li>
    @using (Html.BeginForm("DeleteJoin", "Flavors"))
    {
      @Html.Hidden("joinId", @join.TreatFlavorId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

TreatApp/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TreatApp.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TreatApp/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using TreatApp.Models;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 

@foreach (Flavor flavor in Model)
{
  <li>@Html.ActionLink($"{flavor.Description}", "Details", new { id = flavor.FlavorId })</li>
}

<p>@Html.ActionLink("Add new flavor", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>